/************************************************************************************************
* Name      : PaymentConditionsController
* Purpose   : Controller class to PaymentConditions__c Object
* Author    : Bruna Girão
* Date      : 15/06/2022  
-------------------------------------------------------------------------------------------

15/06/2022           Bruna Girão         create class 
***************************************************************************************************/
public with sharing class PaymentConditionsController {
    
}
